camera_2d_lidar_calibration:
  ros__parameters:
    camera_intrinsic_matrix: [643.545594, 0.000000, 226.319109,
                              0.000000, 642.997723, 141.654344,
                              0.000000, 0.000000, 1.000000]
    distortion_coefficients:
      k1: 0.243390
      k2: -0.864293
      p1: 0.006016
      p2: -0.018107
      k3: 5.958163
    chessboard_square_size: 2.0 # Must be in the same units as camera intrinsic matrix and distortion coefficients. The provided numbers are in units of cm.
    chessboard_inner_width: 11 # Chessboard inner width, defined by OpenCV (https://docs.opencv.org/4.x/d4/d94/tutorial_camera_calibration.html)
    chessboard_inner_height: 8 # Chessboard inner height, defined by OpenCV (https://docs.opencv.org/4.x/d4/d94/tutorial_camera_calibration.html)
    image_topic: /camera/image_raw
    scan_topic: /scan